# Generated by Django 4.0.10 on 2023-04-07 16:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messaging', '0003_file_message_reaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='files',
            field=models.ManyToManyField(null=True, to='messaging.file'),
        ),
        migrations.AlterField(
            model_name='message',
            name='tagged_users',
            field=models.ManyToManyField(null=True, related_name='tagged_message_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
