# Generated by Django 4.0.10 on 2023-04-08 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_alter_message_files_alter_message_tagged_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='replying',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='messaging.message'),
        ),
    ]
