# message actions
CENTRIFUGO_ACTION_MESSAGE_CREATE = "message:create"
CENTRIFUGO_ACTION_MESSAGE_EDIT = "message:edit"
CENTRIFUGO_ACTION_MESSAGE_DELETE = "message:delete"

CENTRIFUGO_ACTION_REACTION_CREATE = "reaction:create"
CENTRIFUGO_ACTION_REACTION_EDIT = "reaction:edit"
CENTRIFUGO_ACTION_REACTION_DELETE = "reaction:delete"
